FROM osrm/osrm-backend:latest

WORKDIR /data

# Download & process Tunisia map (cached by Docker)
RUN wget -q https://download.geofabrik.de/africa/tunisia-latest.osm.pbf && \
    osrm-extract -p /opt/car.lua tunisia-latest.osm.pbf && \
    osrm-partition tunisia-latest.osrm && \
    osrm-customize tunisia-latest.osrm

EXPOSE 5000
CMD ["osrm-routed", "--algorithm", "mld", "tunisia-latest.osrm"]