apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  template:
    metadata:
      labels:
        app: osrm
    spec:
      containers:
        - name: osrm
          image: peterevans/osrm-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OSRM_PBF_URL
              value: "https://download.geofabrik.de/africa/tunisia-latest.osm.pbf"
            - name: OSRM_PROFILE
              value: "car"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /route/v1/driving/10.76,34.74;10.77,34.73
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: osrm
spec:
  selector:
    app: osrm
  ports:
    - port: 5000
      targetPort: 5000